### PR TITLE
#91 make emit statements accessable to hyperledger

### PR DESCRIPTION
**Pull request by Knostpe**
The log emit statement works now for hyperledger literals and variableNames. Blockchain specific variables which are accessable through filters (e.g. block.size / block.hash) are still a todo. Same for testing CSV and XES File output.

Some additional comments have been added to HyperledgerLister and BaseBlockchainListener.

### CODE REVIEW

**Comment by PaulsBecks** [comment]
Btw. I tested CSV -> works.

**Comment by rohrschacht** [comment]
Tested XES as well. Works too! :+1:

**Comment by rohrschacht** [comment]
I removed the very verbose logging from the HyperledgerLogEntryFilterInstruction and added csv and xes output to the HyperBasic manifest. I tested all 3 output methods and they all seem to work fine!

**Review by rohrschacht — APPROVED** [review]
The e2e tests still work fine, so the output instructions still work for the Ethereum. They also seem to work for Hyperledger!

**Pull request merged**
