### PR TITLE
#41 - any order of connection and outputFolder in the manifest file should be accepted by the grammar

### LINKED ISSUE #41: Any order of connection and outputFolder in the manifest file should be accepted by the grammar (depends on #32)

### PR DESCRIPTION
**Pull request by rohrschacht**
Fixes #41.

### CODE REVIEW

**Review by mykola-digtiar — APPROVED** [review]
Looks nice! 👍

**Review by daniil-romanchenko — APPROVED** [review]
I'd approve this but consider the following:
If we build the grammar in such a way, that 'blockchain', 'connection', and 'ouputFolder' are optional, it becomes misleading for the end-user and unclear from the parser and syntax validation. But if we make them mandatory, we'd have to write groovy tests in quite a peculiar way, putting these 3 options in front of each test. 

 I've had such thoughts for quite a long time and I kinda more tend to a second option

**Comment by rohrschacht** [comment]
I agree with you! Let's make it part of the groovy test refactoring into jUnit tests that we already have an issue about.

**Review by Knostpe — APPROVED** [review]
I was about to change the same thing in a separate Branch with more order options between the the three starter parsing rules, but probably better to have it limited on just these two. Also regarding Daniils comment, I just try to get it working locally as being mandatory. Would be great, if we can discuss tomorrow how the tests need to be changed for it.

**Review by daniil-romanchenko — COMMENTED** [review]
Maybe a pair programming session Tobias/Tom would be effective there?

**Pull request merged**
