### PR TITLE
#142 - add comand line flag to abort on error

### LINKED ISSUE #142: Add command line flag to specify whether to shutdown or continue on error

### PR DESCRIPTION
**Pull request by PaulsBecks**
Closes #142.

### CODE REVIEW

**Comment by mykola-digtiar** [comment]
Fixed commit message which was wrapped into ''.

**Review by Knostpe — DISMISSED** [review]
Will test the flag again, when the global exception handler is merged! But looks good.

**Review by rohrschacht — DISMISSED** [review]
We now have e2e tests for the new flag, and Jenkins says they work. Good job! :+1:

**Comment by PaulsBecks** [comment]
> We now have e2e tests for the new flag, and Jenkins says they work. Good job! 👍

Part of this was implemented by you, so good job to you too 👍

**Review by rohrschacht — APPROVED** [review]
I had to force push to trigger the Jenkins build and the subsequent required passed check.

**Review by Knostpe — APPROVED** [review]

**Pull request merged**
