### PR TITLE
#27 - rename EthQL to BcQL to coincide with the purpose of the framework

### LINKED ISSUE #27: Rename EthQL to BcQL to coincide with the purpose of the framework
Please rename everything which is NOT Ethereum specific into (Ethql -> Bql).

### PR DESCRIPTION
**Pull request by rohrschacht**
Fixes #27.

Jenkins build and e2e tests work fine, I also tested all Hyperledger manifests by hand, which were also fine.

### CODE REVIEW

**Review by mykola-digtiar — APPROVED** [review]
👍

**Review by daniil-romanchenko — APPROVED** [review]
Looks fine to me, did you change the e2e as well?

**Comment by rohrschacht** [comment]
Yes, I did change the e2e tests to use the renamed jar file `blf-cmd.jar`. The e2e tests still seem to run correctly on this branch.

**Review by daniil-romanchenko — COMMENTED** [review]
Nice! Feel free to merge, if you're feeling like doing so :D

**Review by Knostpe — APPROVED** [review]

**Pull request merged**
