### PR TITLE
#148 - add exception handling mode to grammar

### LINKED ISSUE #148: Add grammar statement for setting the exception handling mode

### PR DESCRIPTION
**Pull request by Knostpe**
Introduces a exception handling flag in the grammar in form of the Keyword ABORT ON EXCEPTION and a boolean. Because the previously introduced flag would collide with this on, it was decided to take it out.

Closes #148.

### CODE REVIEW

**Comment by mykola-digtiar** [comment]
Conventions. I would suggest `#68 - hotfix dependency error in pom file`
image

**Comment by rohrschacht** [comment]
> Conventions
> image

True. This commit was not needed anymore anyway, because it was already merged as a hotfix - with the right naming convention :)
I force-pushed to try to clean it up a bit.

**Comment by rohrschacht** [comment]
> Conventions. I would suggest `#68 - hotfix dependency error in pom file`

Yes, it is like this in the already merged PR #156.

**Review by mykola-digtiar — APPROVED** [review]
👍

**Review by rohrschacht — APPROVED** [review]
Nice work! :+1:

**Pull request merged**
